### GET / route

GET http://localhost:3000/ 
Content-Type: application/json

### GET users

GET http://localhost:3000/users 
Content-Type: application/json

### GET one user

GET http://localhost:3000/users/1 
Content-Type: application/json

### POST User

POST http://localhost:3000/users 
Content-Type: application/json

{
    "id": 0, 
    "name": "Emberecske", 
    "email": "Utálomagitignore@gmail.com",
    "password": "123."
}

### DELETE user

DELETE http://localhost:3000/users/1
Content-Type: application/json

### PATCH user by id 
PATCH http://localhost:3000/users/1 
Content-Type: application/json

{
    "name": "Pluszember", 
    "age": 25, 
    "gender": "fiúcska"
}

### POST login

POST http://localhost:3000/users/login 
Content-Type: application/json

{
    "email": "ember@gmail.com", 
    "password": "123"
}

### PATCH change password

PATCH http://localhost:3000/users/passmod/2
Content-Type: application/json

{
    "oldpass": "1234",
    "newpass": "123"
}

### PATCH change profile (name, email)
PATCH http://localhost:3000/users/profile/2
Content-Type: application/json

{
    "name": "Emberke", 
    "email": "emberke@gmail.com"
}